import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const webCatalogPath = "/Users/pallas/Documents/marconius.com/fun/whackABraille/scripts/prizeCatalog.js";
const swiftCatalogPath = path.resolve(__dirname, "../Whack A Braille/GameCore/PrizeCatalog.swift");

function loadPrizeCatalog() {
	const source = fs.readFileSync(webCatalogPath, "utf8");
	const sanitized = source
		.replace(/^\s*"use strict";\s*/m, "")
		.replace(/export\s*\{[^}]*\};?\s*$/m, "");

	const sandbox = { module: { exports: null } };
	vm.runInNewContext(`${sanitized}\nmodule.exports = prizeCatalog;`, sandbox, {
		filename: webCatalogPath
	});

	if (!Array.isArray(sandbox.module.exports)) {
		throw new Error("The web prize catalog did not evaluate to an array.");
	}

	return sandbox.module.exports;
}

function swiftString(value) {
	return String(value)
		.replace(/\\/g, "\\\\")
		.replace(/"/g, "\\\"");
}

function buildSwift(prizes) {
	const lines = [
		"import Foundation",
		"",
		"// Generated by scripts/sync_prize_catalog.mjs from",
		"// /Users/pallas/Documents/marconius.com/fun/whackABraille/scripts/prizeCatalog.js",
		"// Do not edit this file by hand.",
		"",
		"enum PrizeCatalog {",
		"",
		"\tstatic let all: [Prize] = ["
	];

	for (const prize of prizes) {
		const maxTickets = prize.maxTickets === null ? "nil" : String(prize.maxTickets);
		lines.push(
			`\t\tPrize(id: "${swiftString(prize.id)}", label: "${swiftString(prize.label)}", minTickets: ${prize.minTickets}, maxTickets: ${maxTickets}, category: "${swiftString(prize.category)}", flavorText: "${swiftString(prize.flavorText ?? "")}"),`
		);
	}

	lines.push(
		"\t]",
		"",
		"\tstatic func eligible(for ticketCount: Int) -> [Prize] {",
		"\t\tall.filter { prize in",
		"\t\t\tguard ticketCount >= prize.minTickets else { return false }",
		"\t\t\tif let maxTickets = prize.maxTickets, ticketCount > maxTickets {",
		"\t\t\t\treturn false",
		"\t\t\t}",
		"\t\t\treturn true",
		"\t\t}",
		"\t}",
		"}",
		""
	);

	return lines.join("\n");
}

const prizes = loadPrizeCatalog();
const swiftSource = buildSwift(prizes);
fs.writeFileSync(swiftCatalogPath, swiftSource);

console.log(`Synced ${prizes.length} prizes into ${swiftCatalogPath}`);
